*&---------------------------------------------------------------------*
*& INCLUDE ZMMPAR52000F02  (To-Be / ALV 모던화 v2 — ALV Setup 계층)
*& 표준: standards/patterns/ALV_MODERN_PATTERN.md  (§3 인스턴스 / §4 필드카탈로그 / §5 생명주기 / §6 이벤트 / §7 Display)
*&---------------------------------------------------------------------*
*& [구조 변경 요약]
*&   구: CREATE_GRID_OBJECT_/ALV_CLEAR_VARIABLE_/BUILD_LAYOUT_/BUILD_SORT_/
*&       BUILD_COLOR_STYLE_/BUILD_EVENT_/DISPLAY_ALV_  ×5벌  (≈2000줄)
*&   신: 역할별 2벌(ALV_DISPLAY_MAIN / ALV_DISPLAY_POP) + 공통 폼
*&   - 그리드: NEW + 메서드체이닝, 풀스크린=SCREEN0 Splitter / 팝업=Docking
*&   - 필드카탈로그: CL_SALV_DATA_DESCR(RTTI) 자동생성 + 화면별 CASE 커스터마이징
*&   - 이벤트: 단일 LCL_EVENT_RECEIVER(=C01) + CREATE_EVENT_RECEIVER 공통 등록
*&   - 생명주기: 자식 FREE 금지(CLEAR만)·팝업 "열기 직전" 해제·FREE 후 FLUSH
*&
*& [완료] BUILD_FIELDCAT 화면별 규칙(FCAT_RULE_0200/0300/0500) 이관 완료.
*&        핸들러/비즈니스 FORM 이관 완료(하단). 로직 무변경.
*& ⚠️ SE38 필수 배선: 팝업 CALL SCREEN(0200/0300/0500) 직전 PERFORM FREE_POPUP_CONTROLS
*&        (F01 및 본 파일 핸들러의 드릴다운 호출부). 패턴 §5-2.
*&---------------------------------------------------------------------*

* 필드카탈로그 텍스트 6종 일괄 설정 매크로
DEFINE _LMC_SET_TEXT.
  <LS_FCAT>-SCRTEXT_S = <LS_FCAT>-SCRTEXT_M = <LS_FCAT>-TOOLTIP =
  <LS_FCAT>-SCRTEXT_L = <LS_FCAT>-COLTEXT  = <LS_FCAT>-REPTEXT = &1.
END-OF-DEFINITION.


*&---------------------------------------------------------------------*
*& Form ALV_DISPLAY_MAIN  — 풀스크린(0100 메인 / 0400 배치) 표시
*&   O01 모듈에서 CHECK GCL_GRID_MAIN IS INITIAL 후 1회 호출
*&---------------------------------------------------------------------*
FORM ALV_DISPLAY_MAIN USING PV_DYNNR TYPE SY-DYNNR.

  FIELD-SYMBOLS <FT_OUT> TYPE STANDARD TABLE.

  " 1) 출력 테이블 바인딩 — 메인은 동적 테이블(CREATE_DYNAMIC_TABLE 생성) + 사전구축 카탈로그
  CASE PV_DYNNR.
    WHEN '0100'. ASSIGN <GT_TABLE> TO <FT_OUT>. GT_FCAT_MAIN = GT_ALV_FIELDCAT_100. " 동적 메인
    WHEN '0400'. ASSIGN <GT_BATCH> TO <FT_OUT>. GT_FCAT_MAIN = GT_ALV_FIELDCAT_400. " 동적 배치(주 진입)
  ENDCASE.
  CHECK <FT_OUT> IS ASSIGNED.

  " 2) 컨테이너/그리드 생성 (SCREEN0 Splitter)
  PERFORM CREATE_INSTANCE_MAIN.

  " 3) 레이아웃 / 정렬 (메인 필드카탈로그는 동적 구축분 사용 → RTTI 미적용)
  PERFORM BUILD_LAYOUT CHANGING GS_LAYOUT_MAIN.
  PERFORM BUILD_SORT_MAIN.

  " 4) 이벤트 등록 + Display
  PERFORM CREATE_EVENT_RECEIVER USING GCL_GRID_MAIN.

  GS_VARIANT_MAIN-REPORT = SY-REPID.
  GCL_ALV_DOCUMENT = NEW CL_DD_DOCUMENT( STYLE = 'ALV_GRID' ).
  GCL_ALV_DOCUMENT->INITIALIZE_DOCUMENT( ).
  GCL_GRID_MAIN->LIST_PROCESSING_EVENTS(
    EXPORTING I_EVENT_NAME = 'TOP_OF_PAGE'
              I_DYNDOC_ID  = GCL_ALV_DOCUMENT ).

  GCL_GRID_MAIN->SET_TABLE_FOR_FIRST_DISPLAY(
    EXPORTING IS_LAYOUT            = GS_LAYOUT_MAIN
              IS_VARIANT           = GS_VARIANT_MAIN
              IT_TOOLBAR_EXCLUDING = GT_EXCLUDE_MAIN
              I_SAVE               = 'A'
    CHANGING  IT_OUTTAB            = <FT_OUT>
              IT_FIELDCATALOG      = GT_FCAT_MAIN
              IT_SORT              = GT_SORT_MAIN ).

ENDFORM.

*&---------------------------------------------------------------------*
*& Form ALV_DISPLAY_POP  — 팝업(0200 그룹RAW / 0300 SIT / 0500 자재문서) 표시
*&---------------------------------------------------------------------*
FORM ALV_DISPLAY_POP USING PV_DYNNR TYPE SY-DYNNR.

  FIELD-SYMBOLS <FT_OUT> TYPE STANDARD TABLE.

  CASE PV_DYNNR.
    WHEN '0200'. ASSIGN GT_RAW_DISP[]  TO <FT_OUT>.   " 그룹 RAW
    WHEN '0300'. ASSIGN GT_SIT_DISP[]  TO <FT_OUT>.   " SIT
    WHEN '0500'. ASSIGN GT_DISP_0500[] TO <FT_OUT>.   " 자재문서
  ENDCASE.
  CHECK <FT_OUT> IS ASSIGNED.

  PERFORM CREATE_INSTANCE_POP.

  PERFORM BUILD_LAYOUT   CHANGING GS_LAYOUT_POP.
  PERFORM BUILD_FIELDCAT USING PV_DYNNR <FT_OUT> CHANGING GT_FCAT_POP.
  PERFORM BUILD_SORT_POP.

  PERFORM CREATE_EVENT_RECEIVER USING GCL_GRID_POP.

  GS_VARIANT_POP-REPORT = SY-REPID.
  GCL_ALV_DOCUMENT = NEW CL_DD_DOCUMENT( STYLE = 'ALV_GRID' ).
  GCL_ALV_DOCUMENT->INITIALIZE_DOCUMENT( ).
  GCL_GRID_POP->LIST_PROCESSING_EVENTS(
    EXPORTING I_EVENT_NAME = 'TOP_OF_PAGE'
              I_DYNDOC_ID  = GCL_ALV_DOCUMENT ).

  GCL_GRID_POP->SET_TABLE_FOR_FIRST_DISPLAY(
    EXPORTING IS_LAYOUT            = GS_LAYOUT_POP
              IS_VARIANT           = GS_VARIANT_POP
              IT_TOOLBAR_EXCLUDING = GT_EXCLUDE_POP
              I_SAVE               = 'A'
    CHANGING  IT_OUTTAB            = <FT_OUT>
              IT_FIELDCATALOG      = GT_FCAT_POP
              IT_SORT              = GT_SORT_POP ).

ENDFORM.

*&---------------------------------------------------------------------*
*& Form CREATE_INSTANCE_MAIN  — 풀스크린 컨테이너/그리드 (SCREEN0)
*&---------------------------------------------------------------------*
FORM CREATE_INSTANCE_MAIN.
  CHECK GCL_GRID_MAIN IS NOT BOUND.

  GCL_SPLIT_MAIN = NEW CL_GUI_SPLITTER_CONTAINER(
                     PARENT  = CL_GUI_CONTAINER=>SCREEN0
                     ROWS    = 2
                     COLUMNS = 1 ).
  GCL_SPLIT_MAIN->SET_ROW_MODE( MODE = CL_GUI_SPLITTER_CONTAINER=>MODE_RELATIVE ).
  GCL_SPLIT_MAIN->SET_ROW_HEIGHT( ID = 1 HEIGHT = 10 ).

  GCL_TOP_CONT_MAIN     = GCL_SPLIT_MAIN->GET_CONTAINER( ROW = 1 COLUMN = 1 ).
  DATA(LCL_GRID_CONT)   = GCL_SPLIT_MAIN->GET_CONTAINER( ROW = 2 COLUMN = 1 ).
  GCL_GRID_MAIN         = NEW CL_GUI_ALV_GRID( I_PARENT = LCL_GRID_CONT ).
ENDFORM.

*&---------------------------------------------------------------------*
*& Form CREATE_INSTANCE_POP  — 팝업 컨테이너/그리드 (Docking)
*&---------------------------------------------------------------------*
FORM CREATE_INSTANCE_POP.
  " 🔒 이전 팝업 컨트롤 잔존 시 먼저 해제 (재오픈 안전 / 패턴 §5-2를 PBO 진입 시점에 적용)
  "    → F01 호출부 수정 없이 드롭인 동작. 그리드/도킹이 살아있으면 정리 후 재생성.
  IF GCL_GRID_POP IS BOUND OR GCL_DOCK_POP IS BOUND.
    PERFORM FREE_POPUP_CONTROLS.
  ENDIF.
  CHECK GCL_GRID_POP IS NOT BOUND.

  GCL_DOCK_POP = NEW CL_GUI_DOCKING_CONTAINER(
                   DYNNR     = SY-DYNNR
                   REPID     = SY-REPID
                   SIDE      = CL_GUI_DOCKING_CONTAINER=>DOCK_AT_TOP
                   EXTENSION = 1500 ).
  DATA(LCL_SPLIT) = NEW CL_GUI_SPLITTER_CONTAINER(
                      PARENT  = GCL_DOCK_POP
                      ROWS    = 2
                      COLUMNS = 1 ).
  LCL_SPLIT->SET_ROW_MODE( MODE = CL_GUI_SPLITTER_CONTAINER=>MODE_RELATIVE ).
  LCL_SPLIT->SET_ROW_HEIGHT( ID = 1 HEIGHT = 20 ).

  GCL_TOP_CONT_POP    = LCL_SPLIT->GET_CONTAINER( ROW = 1 COLUMN = 1 ).
  DATA(LCL_GRID_CONT) = LCL_SPLIT->GET_CONTAINER( ROW = 2 COLUMN = 1 ).
  GCL_GRID_POP        = NEW CL_GUI_ALV_GRID( I_PARENT = LCL_GRID_CONT ).
ENDFORM.

*&---------------------------------------------------------------------*
*& Form CREATE_EVENT_RECEIVER  — 단일 이벤트 리시버 등록 (공통)
*&---------------------------------------------------------------------*
FORM CREATE_EVENT_RECEIVER USING PO_GRID TYPE REF TO CL_GUI_ALV_GRID.
  IF GCL_EVENT IS NOT BOUND.
    CREATE OBJECT GCL_EVENT.
  ENDIF.
  SET HANDLER GCL_EVENT->HANDLE_DOUBLE_CLICK FOR PO_GRID.
  SET HANDLER GCL_EVENT->HANDLE_USER_COMMAND FOR PO_GRID.
  SET HANDLER GCL_EVENT->HANDLE_TOOLBAR      FOR PO_GRID.
  SET HANDLER GCL_EVENT->ON_TOP_OF_PAGE      FOR PO_GRID.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form BUILD_FIELDCAT  — RTTI 자동생성 + 화면별 컬럼 커스터마이징
*&   (구 BUILD_CATEGORY_200/300/500 규칙 이관. 0100/0400은 RTTI 기본)
*&---------------------------------------------------------------------*
FORM BUILD_FIELDCAT USING    PV_DYNNR TYPE SY-DYNNR
                             PT_OUT   TYPE ANY TABLE
                    CHANGING CT_FCAT  TYPE LVC_T_FCAT.

  CLEAR CT_FCAT.

  " RTTI: 출력 테이블 라인타입으로 필드카탈로그 자동 생성 (FS §3-2)
  CT_FCAT = CORRESPONDING #(
    CL_SALV_DATA_DESCR=>READ_STRUCTDESCR(
      CAST CL_ABAP_STRUCTDESCR(
        CAST CL_ABAP_TABLEDESCR(
          CL_ABAP_STRUCTDESCR=>DESCRIBE_BY_DATA( PT_OUT )
        )->GET_TABLE_LINE_TYPE( ) ) ) ).

  LOOP AT CT_FCAT ASSIGNING FIELD-SYMBOL(<LS_FCAT>).
    CLEAR <LS_FCAT>-KEY.

    " 공통: 수량 단위/금액 통화 참조 (KRW ×100 방지, FS §3-6)
    CASE <LS_FCAT>-FIELDNAME.
      WHEN 'MENGE' OR 'WEMNG'.          <LS_FCAT>-QFIELDNAME = 'MEINS'.
      WHEN 'DMBTR' OR 'NETWR' OR 'SITAMT'. <LS_FCAT>-CFIELDNAME = 'WAERS'.
    ENDCASE.

    " 화면별 컬럼 규칙
    CASE PV_DYNNR.
      WHEN '0200'. PERFORM FCAT_RULE_0200 CHANGING <LS_FCAT>.
      WHEN '0300'. PERFORM FCAT_RULE_0300 CHANGING <LS_FCAT>.
      WHEN '0500'. PERFORM FCAT_RULE_0500 CHANGING <LS_FCAT>.
      WHEN OTHERS.  " 0100(메인)/0400(배치): RTTI 기본 (구 BUILD_CATEGORY_100/400 주석처리)
    ENDCASE.
  ENDLOOP.

ENDFORM.

*&---------------------------------------------------------------------*
*& Form FCAT_RULE_0200  — 화면 0200(GT_RAW_DISP) 컬럼 규칙
*&---------------------------------------------------------------------*
FORM FCAT_RULE_0200 CHANGING CS TYPE LVC_S_FCAT.
  " 숨김 컬럼
  CASE CS-FIELDNAME.
    WHEN 'BUKRS' OR 'KUNNR' OR 'KUNNR_TX' OR 'LIFNR' OR 'LIFNR_TX'
      OR 'ZGROUP' OR 'GRUND' OR 'VGART' OR 'BELNR' OR 'GJAHR' OR 'BUZEI'
      OR 'ZIV_CHK' OR 'ZSP_CHK' OR 'CELLTAB' OR 'COLINFO' OR 'INFO'
      OR 'MTART' OR 'SLLAB' OR 'CLABS' OR 'SALK3' OR 'LBKUM' OR 'LABST' OR 'STPRS'.
      CS-NO_OUT = ABAP_TRUE. RETURN.
  ENDCASE.
  " 표시 컬럼 (col_pos / 텍스트 / 합계 / 정렬)
  CASE CS-FIELDNAME.
    WHEN 'MJAHR'.    CS-COL_POS = 0.  CS-COLTEXT = TEXT-F64. CS-JUST = 'C'.
    WHEN 'BUDAT'.    CS-COL_POS = 1.  CS-COLTEXT = TEXT-F65.
    WHEN 'MBLNR'.    CS-COL_POS = 2.  CS-COLTEXT = TEXT-F66.
    WHEN 'ZEILE'.    CS-COL_POS = 3.  CS-COLTEXT = TEXT-F77.
    WHEN 'ZZLOGINO'. CS-COL_POS = 4.  CS-COLTEXT = TEXT-F78.
    WHEN 'MATNR'.    CS-COL_POS = 5.  CS-COLTEXT = TEXT-F51.
    WHEN 'MAKTX'.    CS-COL_POS = 6.  CS-COLTEXT = TEXT-F52.
    WHEN 'WERKS'.    CS-COL_POS = 7.  CS-COLTEXT = TEXT-F58.
    WHEN 'LGORT'.    CS-COL_POS = 8.  CS-COLTEXT = TEXT-F67.
    WHEN 'CHARG'.    CS-COL_POS = 9.  CS-COLTEXT = TEXT-F68.
    WHEN 'MENGE'.    CS-COL_POS = 10. CS-COLTEXT = TEXT-F69. CS-DO_SUM = ABAP_TRUE.
    WHEN 'BWART'.    CS-COL_POS = 12. CS-COLTEXT = TEXT-F71.
    WHEN 'BTEXT'.    CS-COL_POS = 13. CS-COLTEXT = TEXT-F72.
    WHEN 'SOBKZ'.    CS-COL_POS = 14. CS-COLTEXT = TEXT-F73. CS-JUST = 'C'.
    WHEN 'SHKZG'.    CS-COL_POS = 15. CS-COLTEXT = TEXT-F74. CS-JUST = 'C'.
    WHEN 'MEINS'.    CS-COL_POS = 17. CS-COLTEXT = TEXT-F75.
    WHEN 'DMBTR'.    " 금액: P_VAL 체크 시만 표시
      IF P_VAL = ABAP_TRUE.
        CS-COL_POS = 11. CS-COLTEXT = TEXT-F70. CS-DO_SUM = ABAP_TRUE. CS-CFIELDNAME = 'WAERS'.
      ELSE.
        CS-NO_OUT = ABAP_TRUE.
      ENDIF.
    WHEN 'WAERS'.
      IF P_VAL = ABAP_TRUE.
        CS-COL_POS = 18. CS-COLTEXT = TEXT-F76.
      ELSE.
        CS-NO_OUT = ABAP_TRUE.
      ENDIF.
  ENDCASE.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form FCAT_RULE_0300  — 화면 0300(GT_SIT_DISP) 컬럼 규칙
*&---------------------------------------------------------------------*
FORM FCAT_RULE_0300 CHANGING CS TYPE LVC_S_FCAT.
  CASE CS-FIELDNAME.
    WHEN 'EBELN' OR 'EBELP'. CS-KEY = ABAP_TRUE.
    WHEN 'MENGE' OR 'WEMNG' OR 'NETWR'. CS-DO_SUM = ABAP_TRUE.
    WHEN 'SITQTY'.   " In Transit(QTY)
      CS-SCRTEXT_L = CS-REPTEXT = TEXT-N04.
      CS-SCRTEXT_S = CS-SCRTEXT_M = CS-SCRTEXT_L.
      CS-EMPHASIZE = 'C710'. CS-DO_SUM = ABAP_TRUE.
    WHEN 'SITAMT'.   " In Transit(AMT)
      CS-SCRTEXT_L = CS-REPTEXT = TEXT-N05.
      CS-SCRTEXT_S = CS-SCRTEXT_M = CS-SCRTEXT_L.
      CS-EMPHASIZE = 'C710'. CS-DO_SUM = ABAP_TRUE.
  ENDCASE.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form FCAT_RULE_0500  — 화면 0500(GT_DISP_0500) 컬럼 규칙
*&---------------------------------------------------------------------*
FORM FCAT_RULE_0500 CHANGING CS TYPE LVC_S_FCAT.
  " 숨김 컬럼
  CASE CS-FIELDNAME.
    WHEN 'BUKRS' OR 'KUNNR' OR 'KUNNR_TX' OR 'ZGROUP' OR 'GRUND' OR 'VGART'
      OR 'BELNR' OR 'GJAHR' OR 'BUZEI' OR 'ZIV_CHK' OR 'ZSP_CHK'
      OR 'CELLTAB' OR 'COLINFO' OR 'INFO' OR 'MTART' OR 'SALK3'
      OR 'LBKUM' OR 'STPRS' OR 'LABST'.
      CS-NO_OUT = ABAP_TRUE. RETURN.
  ENDCASE.
  " 표시 컬럼
  CASE CS-FIELDNAME.
    WHEN 'MJAHR'.    CS-COL_POS = 0.  CS-COLTEXT = TEXT-F64. CS-JUST = 'C'.
    WHEN 'BUDAT'.    CS-COL_POS = 1.  CS-COLTEXT = TEXT-F65.
    WHEN 'MBLNR'.    CS-COL_POS = 2.  CS-COLTEXT = TEXT-F66.
    WHEN 'ZEILE'.    CS-COL_POS = 3.  CS-COLTEXT = TEXT-F77.
    WHEN 'ZZLOGINO'. CS-COL_POS = 4.  CS-COLTEXT = TEXT-F78.
    WHEN 'WERKS'.    CS-COL_POS = 5.  CS-COLTEXT = TEXT-F58.
    WHEN 'LGORT'.    CS-COL_POS = 6.  CS-COLTEXT = TEXT-F67.
    WHEN 'LIFNR'.    CS-COL_POS = 7.  CS-COLTEXT = TEXT-F59.
    WHEN 'LIFNR_TX'. CS-COL_POS = 8.  CS-COLTEXT = TEXT-F60.
    WHEN 'MATNR'.    CS-COL_POS = 9.  CS-COLTEXT = TEXT-F51.
    WHEN 'MAKTX'.    CS-COL_POS = 10. CS-COLTEXT = TEXT-F52.
    WHEN 'CHARG'.    CS-COL_POS = 11. CS-COLTEXT = TEXT-F68.
    WHEN 'MENGE'.    CS-COL_POS = 12. CS-COLTEXT = TEXT-F69. CS-DO_SUM = ABAP_TRUE.
    WHEN 'BWART'.    CS-COL_POS = 14. CS-COLTEXT = TEXT-F71.
    WHEN 'BTEXT'.    CS-COL_POS = 15. CS-COLTEXT = TEXT-F72.
    WHEN 'SOBKZ'.    CS-COL_POS = 16. CS-COLTEXT = TEXT-F73. CS-JUST = 'C'.
    WHEN 'SHKZG'.    CS-COL_POS = 17. CS-COLTEXT = TEXT-F74. CS-JUST = 'C'.
    WHEN 'MEINS'.    CS-COLTEXT = TEXT-F75. CS-COL_POS = COND #( WHEN P_VAL = ABAP_TRUE THEN 18 ELSE 19 ).
    WHEN 'DMBTR'.    " 금액: P_VAL 체크 시만
      IF P_VAL = ABAP_TRUE.
        CS-COL_POS = 13. CS-COLTEXT = TEXT-F70. CS-DO_SUM = ABAP_TRUE. CS-CFIELDNAME = 'WAERS'.
      ELSE.
        CS-NO_OUT = ABAP_TRUE.
      ENDIF.
    WHEN 'WAERS'.
      IF P_VAL = ABAP_TRUE.
        CS-COL_POS = 19. CS-COLTEXT = TEXT-F76.
      ELSE.
        CS-NO_OUT = ABAP_TRUE.
      ENDIF.
  ENDCASE.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form BUILD_LAYOUT  — 공통 레이아웃
*&---------------------------------------------------------------------*
FORM BUILD_LAYOUT CHANGING CS_LAYO TYPE LVC_S_LAYO.
  CLEAR CS_LAYO.
  CS_LAYO-CWIDTH_OPT = ABAP_TRUE.
  CS_LAYO-ZEBRA      = ABAP_TRUE.
  CS_LAYO-SEL_MODE   = 'D'.   " 원본 동작 보존(단일선택)
  CS_LAYO-CTAB_FNAME = 'COLINFO'.   " 셀 컬러 (기존 사용 시)
  CS_LAYO-STYLEFNAME = 'CELLTAB'.   " 셀 스타일 (기존 사용 시)
ENDFORM.

*&---------------------------------------------------------------------*
*& Form BUILD_SORT_MAIN / BUILD_SORT_POP  — 정렬 (필요 시 화면별 채움)
*&---------------------------------------------------------------------*
FORM BUILD_SORT_MAIN. CLEAR GT_SORT_MAIN. ENDFORM.
FORM BUILD_SORT_POP.  CLEAR GT_SORT_POP.  ENDFORM.

*&---------------------------------------------------------------------*
*& Form FREE_POPUP_CONTROLS  — 팝업 "열기 직전" 호출 (FS §5-1)
*&---------------------------------------------------------------------*
FORM FREE_POPUP_CONTROLS.
  CLEAR GCL_HTML_VIEWER.                       " ⚠️ FREE 금지, CLEAR만
  IF GCL_GRID_POP IS BOUND. GCL_GRID_POP->FREE( ). CLEAR GCL_GRID_POP. ENDIF.
  IF GCL_DOCK_POP IS BOUND. GCL_DOCK_POP->FREE( ). CLEAR GCL_DOCK_POP. ENDIF.
  CLEAR GCL_TOP_CONT_POP.
  CL_GUI_CFW=>FLUSH( ).
ENDFORM.

*&---------------------------------------------------------------------*
*& Form EXIT_RTN  — 풀스크린만 직접 FREE / 팝업은 LEAVE만 (FS §5-3)
*&---------------------------------------------------------------------*
FORM EXIT_RTN.
  CLEAR GCL_HTML_VIEWER.
  CASE SY-DYNNR.
    WHEN '0100' OR '0400'.                     " 풀스크린
      IF GCL_GRID_MAIN  IS BOUND. GCL_GRID_MAIN->FREE( ).  CLEAR GCL_GRID_MAIN.  ENDIF.
      IF GCL_SPLIT_MAIN IS BOUND. GCL_SPLIT_MAIN->FREE( ). CLEAR GCL_SPLIT_MAIN. ENDIF.
      CLEAR GCL_TOP_CONT_MAIN.
      CL_GUI_CFW=>FLUSH( ).
      LEAVE TO SCREEN 0.
    WHEN OTHERS.                               " 팝업
      LEAVE TO SCREEN 0.
  ENDCASE.
ENDFORM.


*&---------------------------------------------------------------------*
*& Form HTML_DISPLAY  — TOP_OF_PAGE HTML 헤더 (모던, 화면별 컨테이너)
*&   생명주기: HTML Viewer는 CLEAR만(FREE 금지) 후 매번 NEW (FS §5,§8)
*&---------------------------------------------------------------------*
FORM HTML_DISPLAY.
  DATA LCL_TOP TYPE REF TO CL_GUI_CONTAINER.
  CASE SY-DYNNR.
    WHEN '0100' OR '0400'. LCL_TOP = GCL_TOP_CONT_MAIN.   " 풀스크린
    WHEN OTHERS.           LCL_TOP = GCL_TOP_CONT_POP.    " 팝업
  ENDCASE.
  CHECK LCL_TOP IS BOUND.

  CLEAR GCL_HTML_VIEWER.                      " ⚠️ FREE 금지, CLEAR만
  GCL_HTML_VIEWER = NEW CL_GUI_HTML_VIEWER( PARENT = LCL_TOP ).

  CALL FUNCTION 'REUSE_ALV_GRID_COMMENTARY_SET'
    EXPORTING DOCUMENT = GCL_ALV_DOCUMENT
              BOTTOM   = SPACE.
  GCL_ALV_DOCUMENT->MERGE_DOCUMENT( ).
  GCL_ALV_DOCUMENT->SET_DOCUMENT_BACKGROUND( PICTURE_ID = CONV SDYDO_KEY( SPACE ) ).
  GCL_ALV_DOCUMENT->HTML_CONTROL = GCL_HTML_VIEWER.
  GCL_ALV_DOCUMENT->DISPLAY_DOCUMENT(
    EXPORTING REUSE_CONTROL = 'X' PARENT = LCL_TOP ).
ENDFORM.



*======================================================================
* [이관] 메인(0100/0400) 동적 필드카탈로그 빌더 — 런타임 이동유형그룹 컬럼
*   CREATE_DYNAMIC_TABLE(F01)에서 호출. 동적 테이블 구조의 원천(정적 RTTI 불가, 패턴 §3-7).
*======================================================================
FORM BUILD_CATEGORY_100  CHANGING PT_ALV_FIELDCAT TYPE LVC_T_FCAT.

  DATA: L_TEXT(30),
        L_COL_POS TYPE I.

  DATA : LT_FCAT TYPE SLIS_T_FIELDCAT_ALV,
         LS_FCAT TYPE LVC_S_FCAT.

  DATA : LT_FCAT_TMP TYPE LVC_T_FCAT,
         LV_FDNAME   TYPE FIELDNAME.

  CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
    EXPORTING
      I_PROGRAM_NAME         = SY-REPID
      I_INTERNAL_TABNAME     = GV_INTTAB100
      I_INCLNAME             = SY-REPID
    CHANGING
      CT_FIELDCAT            = LT_FCAT
    EXCEPTIONS
      INCONSISTENT_INTERFACE = 1
      PROGRAM_ERROR          = 2
      OTHERS                 = 3.
  IF SY-SUBRC <> 0.
  ENDIF.

  DATA : LV_TABNM         LIKE FELD-NAME.
  FIELD-SYMBOLS: <FS_TAB> TYPE STANDARD TABLE.
  CONCATENATE GV_INTTAB100 '[]' INTO LV_TABNM.
  ASSIGN (LV_TABNM) TO <FS_TAB>.

  CALL FUNCTION 'LVC_TRANSFER_FROM_SLIS'
    EXPORTING
      IT_FIELDCAT_ALV = LT_FCAT
    IMPORTING
      ET_FIELDCAT_LVC = PT_ALV_FIELDCAT
    TABLES
      IT_DATA         = <FS_TAB>.

  DATA : PS_FCAT_MENGE TYPE LVC_S_FCAT,
         PS_FCAT_DMBTR TYPE LVC_S_FCAT,
         PS_FCAT_SLLAB TYPE LVC_S_FCAT,
         PS_FCAT_DMAVG TYPE LVC_S_FCAT,
         LV_COLPOS     TYPE LVC_COLPOS.

  CLEAR: PS_FCAT_MENGE, PS_FCAT_DMBTR.

* )Qty/Amt)참조 필드 READ

  READ TABLE PT_ALV_FIELDCAT INTO PS_FCAT_MENGE
                             WITH KEY FIELDNAME = 'MENGE'.
  IF SY-SUBRC EQ 0.
    PS_FCAT_MENGE-NO_ZERO = C_X.
    LV_COLPOS = PS_FCAT_MENGE-COL_POS + 5.

  ENDIF.

  READ TABLE PT_ALV_FIELDCAT INTO PS_FCAT_DMBTR
                             WITH KEY FIELDNAME = 'DMBTR'.
  IF SY-SUBRC EQ 0.
    PS_FCAT_DMBTR-NO_ZERO = C_X.

  ENDIF.

  READ TABLE PT_ALV_FIELDCAT INTO PS_FCAT_DMAVG
                             WITH KEY FIELDNAME = 'DMAVG'.
  IF SY-SUBRC EQ 0.
    PS_FCAT_DMAVG-NO_ZERO = C_X.

  ENDIF.

**----
* Opening Stock(Q'ty / Value) = 기초재고

  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_BI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F01.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_BI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F02.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_BI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F81.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

**----
* Group code

  IF GT_ZMMT0010[] IS INITIAL.
    PERFORM GET_GROUP_ZMMT0010.
  ENDIF.

  LOOP AT GT_ZMMT0010 INTO DATA(LS_ZMMT0010).

    ADD 1 TO LV_COLPOS.
    CLEAR : LS_FCAT.
    MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
    LS_FCAT-COL_POS = LV_COLPOS.
    CONCATENATE PS_FCAT_MENGE-FIELDNAME '_' LS_ZMMT0010-ZGROUP
           INTO LS_FCAT-FIELDNAME.
    CONCATENATE LS_ZMMT0010-ZTEXT TEXT-F91 INTO  LS_FCAT-REPTEXT.
    LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT.
    IF LS_FCAT-FIELDNAME+6(2) = 'GR'.
      LS_FCAT-EMPHASIZE = 'C100'.
    ELSE.
      LS_FCAT-EMPHASIZE = 'C700'.
    ENDIF.
    APPEND LS_FCAT TO PT_ALV_FIELDCAT.

    ADD 1 TO LV_COLPOS.
    CLEAR : LS_FCAT.
    MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
    LS_FCAT-COL_POS = LV_COLPOS.
    CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_' LS_ZMMT0010-ZGROUP
           INTO LS_FCAT-FIELDNAME.
    CONCATENATE LS_ZMMT0010-ZTEXT TEXT-F92 INTO  LS_FCAT-REPTEXT.
    LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT.
    IF LS_FCAT-FIELDNAME+6(2) = 'GR'.
      LS_FCAT-EMPHASIZE = 'C100'.
    ELSE.
      LS_FCAT-EMPHASIZE = 'C700'.
    ENDIF.
    APPEND LS_FCAT TO PT_ALV_FIELDCAT.

    ADD 1 TO LV_COLPOS.
    CLEAR : LS_FCAT.
    MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
    LS_FCAT-COL_POS = LV_COLPOS.
    CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_' LS_ZMMT0010-ZGROUP
           INTO LS_FCAT-FIELDNAME.
    CONCATENATE LS_ZMMT0010-ZTEXT TEXT-F93 INTO  LS_FCAT-REPTEXT.
    LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT.
    IF LS_FCAT-FIELDNAME+6(2) = 'GR'.
      LS_FCAT-EMPHASIZE = 'C100'.
    ELSE.
      LS_FCAT-EMPHASIZE = 'C700'.
    ENDIF.
    APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ENDLOOP.

**----
* Stock In Transit(QTY/AMT) / PO를 통한 재고 => 미사용
*  LS_FCAT-NO_OUT = C_X.               " 숨김처리 / 24.08.20

*  LS_FCAT-NO_OUT = C_X.               " 숨김처리 / 24.08.20

**----
* Closing Stock(Q'ty / Value) = 기말재고

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F03.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F04.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F82.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

**--
*

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_SG_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F05.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_SG_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F06.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.

*  LS_FCAT-NO_OUT = C_X.               " 숨김처리 / 24.08.20

  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_SG_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F83.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

*--------------------------------------------------------------------*
* 참조 필드 삭제

  DELETE PT_ALV_FIELDCAT WHERE FIELDNAME EQ 'MENGE'
                            OR FIELDNAME EQ 'DMBTR'
                            OR FIELDNAME EQ 'DMAVG' .
  SORT PT_ALV_FIELDCAT BY COL_POS.

  LOOP AT PT_ALV_FIELDCAT ASSIGNING <FS_ALV_FIELDCAT>.
    CLEAR <FS_ALV_FIELDCAT>-KEY.

    CASE <FS_ALV_FIELDCAT>-FIELDNAME.
      WHEN 'BUKRS'. " 회사코드
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F50.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.
      WHEN 'MATNR'. " 자재
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F51.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.

*      WHEN 'MAKTX'. " 자재명
*      WHEN 'MAT_DESC'. " 자재명

      WHEN 'WERKS'. " 플랜트
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F58.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LIFNR'. " 벤더
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F59.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LIFNR_TX'. " 벤더명
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F60.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LGORT'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.
      WHEN 'LGOBE'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-COL_OPT = 'X'.
      WHEN 'CHARG'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'CLABS'. " 현재고
        <FS_ALV_FIELDCAT>-EMPHASIZE  = 'C500'.
        <FS_ALV_FIELDCAT>-COLTEXT    = TEXT-F62.
        <FS_ALV_FIELDCAT>-QFIELDNAME = 'MEINS'.
        <FS_ALV_FIELDCAT>-COL_OPT    = 'X'.
      WHEN 'VERPR'. " 현재고 자산
        <FS_ALV_FIELDCAT>-EMPHASIZE  = 'C500'.
        <FS_ALV_FIELDCAT>-COLTEXT    = TEXT-F99.
        <FS_ALV_FIELDCAT>-CFIELDNAME = 'WAERS'.
        <FS_ALV_FIELDCAT>-COL_OPT    = 'X'.
        <FS_ALV_FIELDCAT>-NO_ZERO    = 'X'.

* batch key Start - screen 0400

      WHEN 'SQR'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'SOBKZ'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'PARTNER'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'NAME_ORG1'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-REPTEXT = TEXT-F51.

* batch key end

      WHEN 'MEINS'.

      WHEN 'WAERS'.

      WHEN 'INFO'.
        <FS_ALV_FIELDCAT>-COL_POS = 998.
      WHEN 'MARK'.
        <FS_ALV_FIELDCAT>-COL_POS = 999.

      WHEN 'XXXX'.
        <FS_ALV_FIELDCAT>-NO_OUT = C_X.
    ENDCASE.

  ENDLOOP.

  SORT PT_ALV_FIELDCAT BY COL_POS.

ENDFORM.                    " BUILD_CATEGORY_100

FORM BUILD_CATEGORY_400  CHANGING PT_ALV_FIELDCAT TYPE LVC_T_FCAT.

  LOOP AT PT_ALV_FIELDCAT ASSIGNING <FS_ALV_FIELDCAT>.
    CLEAR <FS_ALV_FIELDCAT>-KEY.

    CASE <FS_ALV_FIELDCAT>-FIELDNAME.
      WHEN 'BUKRS'. " 회사코드
        <FS_ALV_FIELDCAT>-COL_POS = 1.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F50.
        <FS_ALV_FIELDCAT>-KEY = C_X.

*      WHEN 'MAT_DESC'. " 자재명

      WHEN 'MATNR'. " 자재
        <FS_ALV_FIELDCAT>-COL_POS = 2.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F51.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'WERKS'. " 플랜트
        <FS_ALV_FIELDCAT>-COL_POS = 3.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F58.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LGORT'.
        <FS_ALV_FIELDCAT>-COL_POS = 4.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LGOBE'.
        <FS_ALV_FIELDCAT>-COL_POS = 5.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LIFNR'. " 임가공업체
        <FS_ALV_FIELDCAT>-COL_POS = 6.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F59.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LIFNR_TX'. " 업체명
        <FS_ALV_FIELDCAT>-COL_POS = 7.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F60.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'CHARG'.
        <FS_ALV_FIELDCAT>-COL_POS = 8.
        <FS_ALV_FIELDCAT>-KEY = C_X.

      WHEN 'ZZPOR'.
        <FS_ALV_FIELDCAT>-COL_POS = 9.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F81.

      WHEN 'ZZSTOCKCD_TX'.
        <FS_ALV_FIELDCAT>-COL_POS = 10.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F82.

      WHEN 'MATKL'.
        <FS_ALV_FIELDCAT>-COL_POS = 11.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F83.

      WHEN 'MAKTX'. " 자재명
        <FS_ALV_FIELDCAT>-COL_POS = 12.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F52.
        <FS_ALV_FIELDCAT>-NO_OUT = C_X.

      WHEN 'CLABS'. " 현재고
        <FS_ALV_FIELDCAT>-EMPHASIZE  = 'C500'.
        <FS_ALV_FIELDCAT>-COLTEXT    = TEXT-F62.
        <FS_ALV_FIELDCAT>-QFIELDNAME = 'MEINS'.

* batch key Start - screen 0400

      WHEN 'SQR'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'SOBKZ'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'PARTNER'.

      WHEN 'NAME_ORG1'.

        <FS_ALV_FIELDCAT>-REPTEXT = TEXT-F63.

* batch key end

      WHEN 'MEINS'.

      WHEN 'WAERS'.

      WHEN 'INFO'.
        <FS_ALV_FIELDCAT>-COL_POS = 998.
      WHEN 'MARK'.
        <FS_ALV_FIELDCAT>-COL_POS = 999.

      WHEN 'XXXX'.
        <FS_ALV_FIELDCAT>-NO_OUT = C_X.
    ENDCASE.

  ENDLOOP.

ENDFORM.

*======================================================================
* [이관 FORM] 기존 to-be/zmmpar52000f02.abap 에서 로직 변경 없이 이관.
*   구 변수 재매핑: GV_ALV_DOCUMENT→GCL_ALV_DOCUMENT,
*                  GV_ALV_GRID_100/400→GCL_GRID_MAIN
*   (팝업 핸들러 200/300/500은 그리드 객체 직접참조 없음)
*======================================================================

FORM ADD_TEXT  USING PV_TEXT TYPE SDYDO_TEXT_ELEMENT.

  CALL METHOD GCL_ALV_DOCUMENT->ADD_TEXT
    EXPORTING
      TEXT          = PV_TEXT
      SAP_FONTSTYLE = CL_DD_DOCUMENT=>SANS_SERIF
      SAP_EMPHASIS  = CL_DD_DOCUMENT=>EMPHASIS.

ENDFORM.

FORM TOP_OF_PAGE  USING   PV_DYNDOC_ID TYPE REF TO CL_DD_DOCUMENT.

  DATA : LV_TEXT(255) TYPE C,
         LV_VTEXT     LIKE TVKOT-VTEXT.

  DATA : LV_SDATE_TX(20),
         LV_EDATE_TX(20).

  CASE SY-DYNNR.
    WHEN '0100'.  "Main data

* Header

      CLEAR : LV_TEXT.
      LV_TEXT = TEXT-100. "[ Valuated Stock Report - Overview  ]
      CALL METHOD GCL_ALV_DOCUMENT->ADD_TEXT
        EXPORTING
          TEXT         = LV_TEXT
          SAP_FONTSIZE = CL_DD_DOCUMENT=>LARGE
          SAP_EMPHASIS = CL_DD_AREA=>STRONG.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

* Period

      CLEAR : LV_TEXT.
      CONCATENATE S_BUDAT-LOW '~' S_BUDAT-HIGH INTO LV_TEXT.
      CONCATENATE 'Period :' LV_TEXT INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

    WHEN '0200'.  "Group doc. data

* Header

      CLEAR : LV_TEXT.
      CASE GS_DISP_SCR-DYNNR.
        WHEN '0100'.
          LV_TEXT = TEXT-110. "[ Valuated Stock Report - Detail ]
        WHEN '0400'.
          LV_TEXT = TEXT-410. "[ Storage Loc./Batch Stock Report - Detail ]
      ENDCASE.
      CALL METHOD GCL_ALV_DOCUMENT->ADD_TEXT
        EXPORTING
          TEXT         = LV_TEXT
          SAP_FONTSIZE = CL_DD_DOCUMENT=>LARGE
          SAP_EMPHASIS = CL_DD_AREA=>STRONG.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

      CLEAR : LV_TEXT.
      CALL FUNCTION 'CONVERSION_EXIT_MATN1_OUTPUT'
        EXPORTING
          INPUT  = GS_DISP_SCR-MATNR
        IMPORTING
          OUTPUT = GS_DISP_SCR-MATNR.
      CONCATENATE 'Material :' GS_DISP_SCR-MATNR '('GS_DISP_SCR-MAKTX')'
                   INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

      SELECT SINGLE NAME1
      INTO @DATA(LV_NAME1)
      FROM T001W
      WHERE WERKS EQ @GS_DISP_SCR-WERKS.

      CLEAR : LV_TEXT.
      CONCATENATE 'Plant :' GS_DISP_SCR-WERKS '('LV_NAME1')'
                   INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

      CASE GS_DISP_SCR-DYNNR.
        WHEN '0400'.

          SELECT SINGLE LGOBE
          INTO @DATA(LV_LGOBE)
          FROM T001L
          WHERE WERKS EQ @GS_DISP_SCR-WERKS
            AND LGORT EQ @GS_DISP_SCR-LGORT.

          CLEAR : LV_TEXT.
          CONCATENATE 'Storage Location :' GS_DISP_SCR-LGORT '('LV_LGOBE')'
                       INTO LV_TEXT SEPARATED BY SPACE.
          PERFORM ADD_TEXT USING LV_TEXT.
          CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

          CLEAR : LV_TEXT.
          CONCATENATE 'Batch :' GS_DISP_SCR-CHARG
                       INTO LV_TEXT SEPARATED BY SPACE.
          PERFORM ADD_TEXT USING LV_TEXT.
          CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.
      ENDCASE.

      CLEAR : LV_TEXT.
      LV_TEXT = GV_TITLE_200.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

    WHEN '0300'.  "Sit data

      CLEAR : LV_TEXT.
      CALL FUNCTION 'CONVERSION_EXIT_MATN1_OUTPUT'
        EXPORTING
          INPUT  = GS_DISP_SCR-MATNR
        IMPORTING
          OUTPUT = GS_DISP_SCR-MATNR.
      CONCATENATE 'Material :' GS_DISP_SCR-MATNR '('GS_DISP_SCR-MAKTX')'
                   INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

      CLEAR : LV_TEXT.
      CONCATENATE 'Plant :' GS_DISP_SCR-WERKS
                   INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

* Period

      WRITE GV_SDATE_PO TO LV_SDATE_TX.
      CONDENSE LV_SDATE_TX NO-GAPS.
      WRITE GV_EDATE_PO TO LV_EDATE_TX.
      CONDENSE LV_EDATE_TX NO-GAPS.

      CLEAR : LV_TEXT.
      CONCATENATE 'Period :' LV_SDATE_TX '~' LV_EDATE_TX
                   INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

    WHEN '0400'.  "Batch data

* Header

      CLEAR : LV_TEXT.
      LV_TEXT = TEXT-400. "[ Storage Loc./Batch Stock Report - Overview ]
      CALL METHOD GCL_ALV_DOCUMENT->ADD_TEXT
        EXPORTING
          TEXT         = LV_TEXT
          SAP_FONTSIZE = CL_DD_DOCUMENT=>LARGE
          SAP_EMPHASIS = CL_DD_AREA=>STRONG.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

* Period

      CLEAR : LV_TEXT.
      CONCATENATE S_BUDAT-LOW '~' S_BUDAT-HIGH INTO LV_TEXT.
      CONCATENATE 'Period :' LV_TEXT INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

*      " Amount

    WHEN '0500'.  "Sit data

* Header

      CLEAR : LV_TEXT.
      LV_TEXT = TEXT-500. "[ detail view ]
      CALL METHOD GCL_ALV_DOCUMENT->ADD_TEXT
        EXPORTING
          TEXT         = LV_TEXT
          SAP_FONTSIZE = CL_DD_DOCUMENT=>LARGE
          SAP_EMPHASIS = CL_DD_AREA=>STRONG.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.

* Period

      WRITE GV_SDATE_PO TO LV_SDATE_TX.
      CONDENSE LV_SDATE_TX NO-GAPS.
      WRITE GV_EDATE_PO TO LV_EDATE_TX.
      CONDENSE LV_EDATE_TX NO-GAPS.

      CLEAR : LV_TEXT.
      CONCATENATE 'Period :' S_BUDAT-LOW '~' S_BUDAT-HIGH
                   INTO LV_TEXT SEPARATED BY SPACE.
      PERFORM ADD_TEXT USING LV_TEXT.
      CALL METHOD GCL_ALV_DOCUMENT->NEW_LINE.
  ENDCASE.

  PERFORM HTML_DISPLAY .

ENDFORM.

FORM ALV_CLASS_REFRESH  USING P_GRID.

  DATA L_GRID TYPE REF TO CL_GUI_ALV_GRID.
  L_GRID = P_GRID.

* Refresh

  CLEAR GS_ALV_STABLE.
  GS_ALV_STABLE-ROW = 'X'.
  GS_ALV_STABLE-COL = 'X'.

  CALL METHOD L_GRID->REFRESH_TABLE_DISPLAY
    EXPORTING
      IS_STABLE      = GS_ALV_STABLE
      I_SOFT_REFRESH = ''.

ENDFORM.

FORM BUFFER_CLEAR_PROC  USING    PV_REPID
                                 PV_ITNAM.
  DATA: L_MEMORY_ID_CLEAR TYPE STRING,                      "Y7AK023435
        L_MEMORY_ID_HASH  TYPE HASH160.

  CONCATENATE PV_REPID PV_ITNAM INTO L_MEMORY_ID_CLEAR.

  CALL FUNCTION 'CALCULATE_HASH_FOR_CHAR'
    EXPORTING
      DATA   = L_MEMORY_ID_CLEAR                            "RULE 이 Pgm명 + I/T 명
    IMPORTING
      HASH   = L_MEMORY_ID_HASH                             "버퍼 ID : 동적인 내용 이겠쥐~
    EXCEPTIONS
      OTHERS = 4.

  IF SY-SUBRC = 0.
    FREE MEMORY ID L_MEMORY_ID_HASH.                        "Y7AK023435
  ENDIF.

ENDFORM.

FORM HANDLE_DOUBLE_CLICK_100  USING PS_ROW_ID STRUCTURE LVC_S_ROW
                                    PS_COLUMN_ID STRUCTURE LVC_S_COL.

  DATA: LT_TABLE TYPE REF TO DATA,
        LS_TABLE TYPE REF TO DATA.

  FIELD-SYMBOLS: <LS_TABLE> TYPE ANY,
                 <FS_BUKRS> TYPE ANY,
                 <FS_WERKS> TYPE ANY,
                 <FS_MATNR> TYPE ANY,
                 <LS_DISP>  TYPE ANY,
                 <FS_LIFNR> TYPE ANY.

  CREATE DATA LS_TABLE LIKE LINE OF <GT_TABLE>.
  ASSIGN LS_TABLE->* TO <LS_DISP>.

  CHECK PS_ROW_ID-ROWTYPE IS INITIAL.
  READ TABLE <GT_TABLE> ASSIGNING <LS_DISP>
                        INDEX PS_ROW_ID-INDEX.

  ASSIGN COMPONENT: 'WERKS' OF STRUCTURE <LS_DISP> TO <FS_WERKS>,
                    'MATNR' OF STRUCTURE <LS_DISP> TO <FS_MATNR>,
                    'lifnr' OF STRUCTURE <LS_DISP> TO <FS_LIFNR>.

  CHECK SY-SUBRC = 0.

  CASE PS_COLUMN_ID-FIELDNAME.
    WHEN 'MATNR' OR 'MAKTX'.
      IF <FS_MATNR> IS INITIAL.
        MESSAGE S000 WITH 'There is no Material' DISPLAY LIKE 'E'.
      ELSE.
        SET PARAMETER ID 'MAT' FIELD <FS_MATNR>.
        SET PARAMETER ID 'WRK' FIELD <FS_WERKS>.
        SET PARAMETER ID 'MXX' FIELD 'K'.
        CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.
      ENDIF.
    WHEN 'LIFNR' OR 'LIFNR_TX'.
      DATA: KDY_VAL(8) VALUE '/110'.
      SET PARAMETER ID 'LIF' FIELD <FS_LIFNR>.   " Pass the vendor
      SET PARAMETER ID 'KDY' FIELD KDY_VAL.
      CALL TRANSACTION 'XK03' AND SKIP FIRST SCREEN.

    WHEN OTHERS.
      CASE PS_COLUMN_ID-FIELDNAME+0(6).
        WHEN 'MENGE_' OR 'DMBTR_' OR 'DMAVG_'.
          IF PS_COLUMN_ID-FIELDNAME EQ 'MENGE_SIT' OR
             PS_COLUMN_ID-FIELDNAME EQ 'DMBTR_SIT' OR
             PS_COLUMN_ID-FIELDNAME EQ 'DMAVG_SIT'.  "미착품

            PERFORM SHOW_SIT_DATA CHANGING <LS_DISP>.

          ELSE.

            PERFORM SHOW_GROUP_RAW USING PS_COLUMN_ID-FIELDNAME
                                         '0100'
                                   CHANGING <LS_DISP>.

          ENDIF.
        WHEN OTHERS.
      ENDCASE.

  ENDCASE.

*    EXPORTING

ENDFORM.

FORM HANDLE_DOUBLE_CLICK_200  USING PS_ROW_ID STRUCTURE LVC_S_ROW
                                    PS_COLUMN_ID STRUCTURE LVC_S_COL.

  CHECK PS_ROW_ID-ROWTYPE IS INITIAL.
  READ TABLE GT_RAW_DISP ASSIGNING FIELD-SYMBOL(<FS_RAW>)
                        INDEX PS_ROW_ID-INDEX.

  CHECK SY-SUBRC = 0.

  CASE PS_COLUMN_ID-FIELDNAME.
    WHEN 'MATNR' OR 'MAKTX'.
      IF <FS_RAW>-MATNR IS INITIAL.
        MESSAGE S000 WITH 'There is no Material' DISPLAY LIKE 'E'.
      ELSE.
        SET PARAMETER ID 'MAT' FIELD <FS_RAW>-MATNR.
        SET PARAMETER ID 'WRK' FIELD <FS_RAW>-WERKS.
        SET PARAMETER ID 'MXX' FIELD 'K'.
        CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.
      ENDIF.

    WHEN 'CHARG'.
      SET PARAMETER ID 'MAT' FIELD <FS_RAW>-MATNR.
      SET PARAMETER ID 'WRK' FIELD <FS_RAW>-WERKS.
      SET PARAMETER ID 'CHA' FIELD <FS_RAW>-CHARG.
      CALL TRANSACTION 'MSC3N' AND SKIP FIRST SCREEN.

    WHEN 'BELNR' OR 'GJAHR' OR 'BUZEI'.
      IF <FS_RAW>-BELNR IS NOT INITIAL.
        IF <FS_RAW>-ZSP_CHK EQ C_X.
          SET PARAMETER ID 'MLN' FIELD <FS_RAW>-BELNR.
          SET PARAMETER ID 'MLJ' FIELD <FS_RAW>-GJAHR.
          CALL TRANSACTION 'CKMB' AND SKIP FIRST SCREEN.
        ELSE.
          SET PARAMETER ID 'RBN' FIELD <FS_RAW>-BELNR.
          SET PARAMETER ID 'GJR' FIELD <FS_RAW>-GJAHR.
          CALL TRANSACTION 'MIR4' AND SKIP FIRST SCREEN.
        ENDIF.
      ENDIF.

    WHEN OTHERS.
      IF <FS_RAW>-MBLNR IS NOT INITIAL.
        IF <FS_RAW>-ZSP_CHK EQ C_X.

          SET PARAMETER ID 'BLN' FIELD <FS_RAW>-MBLNR.
          SET PARAMETER ID 'BUK' FIELD <FS_RAW>-BUKRS.
          SET PARAMETER ID 'GJR' FIELD <FS_RAW>-MJAHR.
          CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.

        ELSE.
          CALL FUNCTION 'MIGO_DIALOG'
            EXPORTING
              I_ACTION            = 'A04'
              I_REFDOC            = 'R02'
              I_MBLNR             = <FS_RAW>-MBLNR
              I_MJAHR             = <FS_RAW>-MJAHR
            EXCEPTIONS
              ILLEGAL_COMBINATION = 1
              OTHERS              = 2.
          IF SY-SUBRC <> 0.

* Implement suitable error handling here

          ENDIF.
        ENDIF.
      ENDIF.
  ENDCASE.

ENDFORM.

FORM HANDLE_DOUBLE_CLICK_300  USING PS_ROW_ID STRUCTURE LVC_S_ROW
                                    PS_COLUMN_ID STRUCTURE LVC_S_COL.

  CHECK PS_ROW_ID-ROWTYPE IS INITIAL.
  READ TABLE GT_SIT_DISP ASSIGNING FIELD-SYMBOL(<FS_SIT>)
                        INDEX PS_ROW_ID-INDEX.

  CHECK SY-SUBRC = 0.

  PERFORM SHOW_GRLIST_DATA CHANGING <FS_SIT>.

ENDFORM.

FORM HANDLE_DOUBLE_CLICK_400  USING PS_ROW_ID STRUCTURE LVC_S_ROW
                                    PS_COLUMN_ID STRUCTURE LVC_S_COL.

  DATA: LT_TABLE TYPE REF TO DATA,
        LS_TABLE TYPE REF TO DATA.

  FIELD-SYMBOLS: <LS_TABLE> TYPE ANY,
                 <FS_BUKRS> TYPE ANY,
                 <FS_WERKS> TYPE ANY,
                 <FS_MATNR> TYPE ANY,
                 <FS_CHARG> TYPE ANY,
                 <LS_DISP>  TYPE ANY,
                 <FS_LIFNR> TYPE ANY.

  CREATE DATA LS_TABLE LIKE LINE OF <GT_BATCH>.
  ASSIGN LS_TABLE->* TO <LS_DISP>.

  CHECK PS_ROW_ID-ROWTYPE IS INITIAL.
  READ TABLE <GT_BATCH> ASSIGNING <LS_DISP>
                        INDEX PS_ROW_ID-INDEX.

  ASSIGN COMPONENT: 'WERKS' OF STRUCTURE <LS_DISP> TO <FS_WERKS>,
                    'MATNR' OF STRUCTURE <LS_DISP> TO <FS_MATNR>,
                    'CHARG' OF STRUCTURE <LS_DISP> TO <FS_CHARG>,
                    'LIFNR' OF STRUCTURE <LS_DISP> TO <FS_LIFNR>.

  CHECK SY-SUBRC = 0.

  CASE PS_COLUMN_ID-FIELDNAME.
    WHEN 'MATNR' OR 'MAKTX'.
      IF <FS_MATNR> IS INITIAL.
        MESSAGE S000 WITH 'There is no Material' DISPLAY LIKE 'E'.
      ELSE.
        SET PARAMETER ID 'MAT' FIELD <FS_MATNR>.
        SET PARAMETER ID 'WRK' FIELD <FS_WERKS>.
        SET PARAMETER ID 'MXX' FIELD 'K'.
        CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.
      ENDIF.

    WHEN 'CHARG'.
      SET PARAMETER ID 'MAT' FIELD <FS_MATNR>.
      SET PARAMETER ID 'WRK' FIELD <FS_WERKS>.
      SET PARAMETER ID 'CHA' FIELD <FS_CHARG>.
      CALL TRANSACTION 'MSC3N' AND SKIP FIRST SCREEN.

    WHEN 'LIFNR' OR 'LIFNR_TX'.
      DATA: KDY_VAL(8) VALUE '/110'.
      SET PARAMETER ID 'LIF' FIELD <FS_LIFNR>.   " Pass the vendor
      SET PARAMETER ID 'KDY' FIELD KDY_VAL.
      CALL TRANSACTION 'XK03' AND SKIP FIRST SCREEN.

    WHEN OTHERS.

      CASE PS_COLUMN_ID-FIELDNAME+0(6).
        WHEN 'MENGE_' OR 'DMBTR_'.
          IF PS_COLUMN_ID-FIELDNAME EQ 'MENGE_BI' OR
             PS_COLUMN_ID-FIELDNAME EQ 'MENGE_EI' OR
             PS_COLUMN_ID-FIELDNAME EQ 'MENGE_SG_EI'.

          ELSEIF PS_COLUMN_ID-FIELDNAME EQ 'MENGE_SIT'.

            PERFORM SHOW_SIT_DATA_BATCH CHANGING <LS_DISP>.

          ELSE.

            PERFORM SHOW_GROUP_RAW USING PS_COLUMN_ID-FIELDNAME
                                         '0400'
                                   CHANGING <LS_DISP>.

          ENDIF.
        WHEN OTHERS.
      ENDCASE.

  ENDCASE.

ENDFORM.

FORM HANDLE_DOUBLE_CLICK_500  USING PS_ROW_ID STRUCTURE LVC_S_ROW
                                    PS_COLUMN_ID STRUCTURE LVC_S_COL.

  CHECK PS_ROW_ID-ROWTYPE IS INITIAL.
  READ TABLE GT_DISP_0500 ASSIGNING FIELD-SYMBOL(<FS_RAW>)
                        INDEX PS_ROW_ID-INDEX.

  CHECK SY-SUBRC = 0.

  CASE PS_COLUMN_ID-FIELDNAME.
    WHEN 'MATNR' OR 'MAKTX'.
      IF <FS_RAW>-MATNR IS INITIAL.
        MESSAGE S000 WITH 'There is no Material' DISPLAY LIKE 'E'.
      ELSE.
        SET PARAMETER ID 'MAT' FIELD <FS_RAW>-MATNR.
        SET PARAMETER ID 'WRK' FIELD <FS_RAW>-WERKS.
        SET PARAMETER ID 'MXX' FIELD 'K'.
        CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.
      ENDIF.

    WHEN 'CHARG'.
      SET PARAMETER ID 'MAT' FIELD <FS_RAW>-MATNR.
      SET PARAMETER ID 'WRK' FIELD <FS_RAW>-WERKS.
      SET PARAMETER ID 'CHA' FIELD <FS_RAW>-CHARG.
      CALL TRANSACTION 'MSC3N' AND SKIP FIRST SCREEN.

    WHEN 'BELNR' OR 'GJAHR' OR 'BUZEI'.
      IF <FS_RAW>-BELNR IS NOT INITIAL.
        IF <FS_RAW>-ZSP_CHK EQ C_X.
          SET PARAMETER ID 'MLN' FIELD <FS_RAW>-BELNR.
          SET PARAMETER ID 'MLJ' FIELD <FS_RAW>-GJAHR.
          CALL TRANSACTION 'CKMB' AND SKIP FIRST SCREEN.
        ELSE.
          SET PARAMETER ID 'RBN' FIELD <FS_RAW>-BELNR.
          SET PARAMETER ID 'GJR' FIELD <FS_RAW>-GJAHR.
          CALL TRANSACTION 'MIR4' AND SKIP FIRST SCREEN.
        ENDIF.
      ENDIF.

    WHEN OTHERS.
      IF <FS_RAW>-MBLNR IS NOT INITIAL.
        IF <FS_RAW>-ZSP_CHK EQ C_X.

          SET PARAMETER ID 'BLN' FIELD <FS_RAW>-MBLNR.
          SET PARAMETER ID 'BUK' FIELD <FS_RAW>-BUKRS.
          SET PARAMETER ID 'GJR' FIELD <FS_RAW>-MJAHR.
          CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.

        ELSE.
          CALL FUNCTION 'MIGO_DIALOG'
            EXPORTING
              I_ACTION            = 'A04'
              I_REFDOC            = 'R02'
              I_MBLNR             = <FS_RAW>-MBLNR
              I_MJAHR             = <FS_RAW>-MJAHR
            EXCEPTIONS
              ILLEGAL_COMBINATION = 1
              OTHERS              = 2.
          IF SY-SUBRC <> 0.

* Implement suitable error handling here

          ENDIF.
        ENDIF.
      ENDIF.
  ENDCASE.

ENDFORM.

FORM HANDLER_TOOLBAR USING PO_OBJECT TYPE REF TO CL_ALV_EVENT_TOOLBAR_SET
                           PO_SENDER TYPE REF TO CL_GUI_ALV_GRID.

  " Internal Table PO_OBJECT->MT_TOOLBAR 를 위한 작업공간
  " PO_OBJECT->MT_TOOLBAR >>> 클래스의 Attribute ( Public , Instance )
  DATA LS_TOOLBAR LIKE LINE OF PO_OBJECT->MT_TOOLBAR.

  DATA : LV_INVOICE TYPE I,
         LV_OK      TYPE I,
         LV_ING     TYPE I,
         LV_NO      TYPE I.

  CASE PO_SENDER.
    WHEN GCL_GRID_MAIN.

* 구분자 =>> |

      CLEAR LS_TOOLBAR.
      LS_TOOLBAR-BUTN_TYPE = 3. " 구분자
      APPEND LS_TOOLBAR TO PO_OBJECT->MT_TOOLBAR.

* 버튼 추가 =>> 전체조회

      CLEAR LS_TOOLBAR.
      LS_TOOLBAR-BUTN_TYPE = 0. " 사용가능 배치번호 O/X
      LS_TOOLBAR-FUNCTION = GC_INVOICE.
      LS_TOOLBAR-ICON = ICON_SELECT_DETAIL.
      LS_TOOLBAR-TEXT = TEXT-B11.
      APPEND LS_TOOLBAR TO PO_OBJECT->MT_TOOLBAR.

  ENDCASE.

ENDFORM.

FORM HANDLER_TOOLBAR_0400 USING PO_OBJECT TYPE REF TO CL_ALV_EVENT_TOOLBAR_SET
                                PO_SENDER TYPE REF TO CL_GUI_ALV_GRID.

  " Internal Table PO_OBJECT->MT_TOOLBAR 를 위한 작업공간
  " PO_OBJECT->MT_TOOLBAR >>> 클래스의 Attribute ( Public , Instance )
  DATA LS_TOOLBAR LIKE LINE OF PO_OBJECT->MT_TOOLBAR.

  DATA : LV_INVOICE TYPE I,
         LV_OK      TYPE I,
         LV_ING     TYPE I,
         LV_NO      TYPE I.

  CASE PO_SENDER.
    WHEN GCL_GRID_MAIN.

* 구분자 =>> |

      CLEAR LS_TOOLBAR.
      LS_TOOLBAR-BUTN_TYPE = 3. " 구분자
      APPEND LS_TOOLBAR TO PO_OBJECT->MT_TOOLBAR.

* 버튼 추가 =>> 전체조회

      CLEAR LS_TOOLBAR.
      LS_TOOLBAR-BUTN_TYPE = 0. " 사용가능 배치번호 O/X
      LS_TOOLBAR-FUNCTION = GC_INVOICE.
      LS_TOOLBAR-ICON = ICON_SELECT_DETAIL.
      LS_TOOLBAR-TEXT = TEXT-B11.
      APPEND LS_TOOLBAR TO PO_OBJECT->MT_TOOLBAR.

  ENDCASE.

ENDFORM.

FORM HANDLE_USER_COMMAND_100  USING PV_UCOMM   TYPE SY-UCOMM
                                    PO_SENDER  TYPE REF TO CL_GUI_ALV_GRID.

  DATA LT_INDEX_ROWS TYPE LVC_T_ROW.
  DATA LS_INDEX_ROW  LIKE LINE OF LT_INDEX_ROWS.
  DATA LS_MATDOC     LIKE LINE OF GT_DISP_0500.
  DATA LS_GROUP      LIKE LINE OF GT_GROUP.
  DATA: LT_TABLE TYPE REF TO DATA,
        LS_TABLE TYPE REF TO DATA.

  FIELD-SYMBOLS: <LS_TABLE> TYPE ANY,
                 <FS_BUKRS> TYPE ANY,
                 <FS_WERKS> TYPE ANY,
                 <FS_MATNR> TYPE ANY,
                 <LS_DISP>  TYPE ANY,
                 <FS_LIFNR> TYPE ANY.

  CREATE DATA LS_TABLE LIKE LINE OF <GT_TABLE>.
  ASSIGN LS_TABLE->* TO <LS_DISP>.

  CASE PO_SENDER.
    WHEN GCL_GRID_MAIN.

      CASE PV_UCOMM.
        WHEN GC_INVOICE.

          CALL METHOD GCL_GRID_MAIN->GET_SELECTED_ROWS
            IMPORTING
              ET_INDEX_ROWS = LT_INDEX_ROWS.     " Indexes of Selected Rows

          IF LT_INDEX_ROWS[] IS INITIAL.
            " Select line to display detail item.
            MESSAGE S081 DISPLAY LIKE 'E'.
          ELSE.

            CLEAR: GT_MATDOC[], GT_DISP_0500[].

            LOOP AT LT_INDEX_ROWS INTO LS_INDEX_ROW WHERE ROWTYPE IS INITIAL.

*             <GS_TABLE>.

              READ TABLE <GT_TABLE> INTO <LS_DISP> INDEX LS_INDEX_ROW-INDEX.

              ASSIGN COMPONENT: 'BUKRS' OF STRUCTURE <LS_DISP> TO <FS_BUKRS>,
                                'WERKS' OF STRUCTURE <LS_DISP> TO <FS_WERKS>,
                                'MATNR' OF STRUCTURE <LS_DISP> TO <FS_MATNR>,
                                'LIFNR' OF STRUCTURE <LS_DISP> TO <FS_LIFNR>.

* Read Matdoc

              SELECT A~BUKRS          " 회사코드
                     A~MJAHR          " 자재문서연도
                     A~MBLNR          " 자재문서번호
                     A~MATNR          " 자재번호
                     B~MAKTX          " 자재내역(명)
                     A~WERKS          " 플랜트
                     A~LGORT          " 저장위치
                     A~CHARG          " 배치(Batch)
                     A~SOBKZ          " 특별재고지시자
                     A~EMLIF     AS LIFNR
                     D~NAME_ORG1 AS LIFNR_TX " 공급처명
                     A~MENGE          " 수량
                     A~DMBTR          " 금액(현지통화)
                     A~WAERS          " 통화
                     A~BWART          " 이동유형

*                     H~BEIKZ           " MPI 추가

                     A~GRUND          " 이동사유
                     A~SHKZG          " 차변/대변 지시자
                     A~MEINS          " 기본단위
                     A~WAERS          " 통화
                     A~ZEILE          " 자재문서항목
                     E~MTART          " 자재유형
                     A~VGART            "CHECK
                     A~BUDAT            " 전기일 추가
                     A~SALK3          " 총평가액
                     A~LBKUM          " 총평가재고수량

                INTO CORRESPONDING FIELDS OF TABLE GT_DISP_0500
                FROM MATDOC AS A
                LEFT OUTER JOIN MAKT AS B
                  ON B~MATNR EQ A~MATNR
                 AND B~SPRAS EQ SY-LANGU
                LEFT OUTER JOIN BUT000 AS D
                  ON D~PARTNER EQ A~EMLIF
                LEFT OUTER JOIN MARA AS E
                  ON E~MATNR EQ A~MATNR
                JOIN ZMMPAT52010 AS H
                  ON H~BWART EQ A~BWART
               WHERE A~RECORD_TYPE EQ 'MDOC'
                 AND A~BUDAT BETWEEN S_BUDAT-LOW AND S_BUDAT-HIGH
                 AND A~MATNR EQ <FS_MATNR>
                 AND A~WERKS EQ <FS_WERKS>
                 AND A~EMLIF EQ <FS_LIFNR>
                 AND A~CHARG IN GR_CHARG
                 AND A~SOBKZ EQ 'O'.

              APPEND LINES OF GT_DISP_0500 TO GT_MATDOC[].
              CLEAR GT_DISP_0500[].
            ENDLOOP.

            IF GT_MATDOC[] IS INITIAL.
              " No data found
              MESSAGE S082 DISPLAY LIKE 'E'.
              EXIT.
            ENDIF.

*--STO 금액 변환

            DATA(LT_STO) = GT_MATDOC[].
            DELETE LT_STO WHERE DMBTR NE 0.
            DELETE LT_STO WHERE BWART NE '101'.

            SELECT A~MJAHR,           " 자재문서연도
                   A~MBLNR,           " 자재문서번호
                   A~ZEILE,           " 자재문서항목
                   A~MATNR,           " 자재번호
                   A~WERKS,           " 플랜트
                   A~LGORT_CID AS LGORT, " 저장위치
                   A~CHARG_CID AS CHARG, " 배치(Batch)
                   A~DMBTR            " 금액(현지통화)
              FROM MATDOC AS A JOIN @LT_STO AS B
                                 ON A~MJAHR     = B~MJAHR
                                AND A~MBLNR     = B~MBLNR
                                AND A~ZEILE     = B~ZEILE
                                AND A~MATNR     = B~MATNR
                                AND A~WERKS     = B~WERKS
                                AND A~LGORT_CID = B~LGORT
                                AND A~CHARG_CID = B~CHARG
             WHERE A~RECORD_TYPE = 'MDOC_CP'
               AND A~LBBSA_SID   = '06'
               AND A~DMBTR NE 0
              INTO TABLE @DATA(LT_STO_DMBTR).
            SORT LT_STO_DMBTR BY MJAHR MBLNR ZEILE MATNR WERKS LGORT CHARG.

*-- Group 및 차/대 반영

            LOOP AT GT_MATDOC[] INTO LS_MATDOC.

*--STO 금액 변환

              IF LS_MATDOC-BWART = '101' AND LS_MATDOC-DMBTR = 0.
                READ TABLE LT_STO_DMBTR INTO DATA(LS_STO_DMBTR) WITH KEY MJAHR = LS_MATDOC-MJAHR
                                                                         MBLNR = LS_MATDOC-MBLNR
                                                                         ZEILE = LS_MATDOC-ZEILE
                                                                         MATNR = LS_MATDOC-MATNR
                                                                         WERKS = LS_MATDOC-WERKS
                                                                         LGORT = LS_MATDOC-LGORT
                                                                         CHARG = LS_MATDOC-CHARG
                                                                         BINARY SEARCH.
                IF SY-SUBRC = 0.
                  LS_MATDOC-DMBTR = LS_STO_DMBTR-DMBTR.
                ENDIF.
              ENDIF.
              CLEAR LS_STO_DMBTR.

              READ TABLE GT_GROUP INTO LS_GROUP
                                  WITH KEY BWART = LS_MATDOC-BWART
                                  BINARY SEARCH.
              IF SY-SUBRC NE 0.
                CASE LS_MATDOC-SHKZG.
                  WHEN 'H'.
                    LS_MATDOC-ZGROUP = GV_GI_ETC.
                  WHEN 'S'.
                    LS_MATDOC-ZGROUP = GV_GR_ETC.
                ENDCASE.
              ELSE.
                LS_MATDOC-ZGROUP = LS_GROUP-ZGROUP.
              ENDIF.

              IF ( LS_MATDOC-ZGROUP(2) = 'GR' AND LS_MATDOC-SHKZG = 'H' ) OR
                 ( LS_MATDOC-ZGROUP(2) = 'GI' AND LS_MATDOC-SHKZG = 'H' ).
                LS_MATDOC-MENGE = LS_MATDOC-MENGE * -1.
                LS_MATDOC-DMBTR = LS_MATDOC-DMBTR * -1.
              ELSE.

*              <FS_RAW>-MENGE.
*              <FS_RAW>-DMBTR.

              ENDIF.

              CASE LS_MATDOC-BWART.
                WHEN '541'.
                  LS_MATDOC-SALK3 = LS_MATDOC-SALK3 / LS_MATDOC-LBKUM.
                  LS_MATDOC-DMBTR = LS_MATDOC-MENGE * LS_MATDOC-SALK3.

                WHEN '542'.
                  LS_MATDOC-SALK3 = LS_MATDOC-SALK3 / LS_MATDOC-LBKUM.
                  LS_MATDOC-DMBTR = LS_MATDOC-MENGE * LS_MATDOC-SALK3.

              ENDCASE.

*-- Mvt.Text 추가

              SELECT SINGLE BTEXT
                     INTO @DATA(LV_BTEXT)
                     FROM T156T
                     WHERE BWART EQ @LS_MATDOC-BWART
                       AND SPRAS EQ @SY-LANGU.

              LS_MATDOC-BTEXT = LV_BTEXT.

              APPEND LS_MATDOC TO GT_DISP_0500.
            ENDLOOP.

*-- 정의된 Mvt에 포함되지 않은 값은 Delete

            LOOP AT GT_DISP_0500 ASSIGNING FIELD-SYMBOL(<FS_DISP_0500>).

              READ TABLE GT_GROUP WITH KEY BWART = <FS_DISP_0500>-BWART
                                  TRANSPORTING NO FIELDS
                                  BINARY SEARCH.

              IF SY-SUBRC <> 0.
                DELETE TABLE GT_DISP_0500 FROM <FS_DISP_0500>.

              ENDIF.

              IF <FS_DISP_0500>-MENGE < 0.
                <FS_DISP_0500>-INFO = 'C600'.
              ELSE.
                <FS_DISP_0500>-INFO = 'C100'.
              ENDIF.

            ENDLOOP.

            SORT GT_DISP_0500 BY BUDAT LIFNR MATNR CHARG.

            CALL SCREEN 0500 STARTING AT 10 2
            ENDING AT 170 30.

          ENDIF.
      ENDCASE.
  ENDCASE.

ENDFORM.

FORM HANDLE_USER_COMMAND_400  USING PV_UCOMM   TYPE SY-UCOMM
                                    PO_SENDER  TYPE REF TO CL_GUI_ALV_GRID.

  DATA LT_INDEX_ROWS TYPE LVC_T_ROW.
  DATA LS_INDEX_ROW  LIKE LINE OF LT_INDEX_ROWS.
  DATA LS_MATDOC     LIKE LINE OF GT_DISP_0500.
  DATA LS_GROUP      LIKE LINE OF GT_GROUP.
  DATA: LT_TABLE TYPE REF TO DATA,
        LS_TABLE TYPE REF TO DATA.

  FIELD-SYMBOLS: <LS_TABLE> TYPE ANY,
                 <FS_BUKRS> TYPE ANY,
                 <FS_WERKS> TYPE ANY,
                 <FS_LGORT> TYPE ANY,
                 <FS_MATNR> TYPE ANY,
                 <LS_DISP>  TYPE ANY,
                 <FS_LIFNR> TYPE ANY,
                 <FS_CHARG> TYPE ANY.

  CREATE DATA LS_TABLE LIKE LINE OF <GT_BATCH>.
  ASSIGN LS_TABLE->* TO <LS_DISP>.

  CASE PO_SENDER.
    WHEN GCL_GRID_MAIN.

      CASE PV_UCOMM.
        WHEN GC_INVOICE.

          CALL METHOD GCL_GRID_MAIN->GET_SELECTED_ROWS
            IMPORTING
              ET_INDEX_ROWS = LT_INDEX_ROWS.     " Indexes of Selected Rows

          IF LT_INDEX_ROWS[] IS INITIAL.
            " Select line to display detail item.
            MESSAGE S081 DISPLAY LIKE 'E'.
          ELSE.

            CLEAR: GT_MATDOC[], GT_DISP_0500[].

            LOOP AT LT_INDEX_ROWS INTO LS_INDEX_ROW WHERE ROWTYPE IS INITIAL.

*             <GS_TABLE>.

              READ TABLE <GT_BATCH> INTO <LS_DISP> INDEX LS_INDEX_ROW-INDEX.

              ASSIGN COMPONENT: 'BUKRS' OF STRUCTURE <LS_DISP> TO <FS_BUKRS>,
                                'WERKS' OF STRUCTURE <LS_DISP> TO <FS_WERKS>,
                                'LGORT' OF STRUCTURE <LS_DISP> TO <FS_LGORT>,
                                'MATNR' OF STRUCTURE <LS_DISP> TO <FS_MATNR>,
                                'LIFNR' OF STRUCTURE <LS_DISP> TO <FS_LIFNR>,
                                'CHARG' OF STRUCTURE <LS_DISP> TO <FS_CHARG>.

* Read Matdoc
* 사급업체 없으면 일반 케이스 라인

              IF <FS_LIFNR> IS INITIAL.
                SELECT A~BUKRS        " 회사코드
                       A~MJAHR        " 자재문서연도
                       A~MBLNR        " 자재문서번호
                       A~MATNR        " 자재번호
                       B~MAKTX        " 자재내역(명)
                       A~WERKS        " 플랜트
                       A~LGORT        " 저장위치
                       A~CHARG        " 배치(Batch)
                       A~SOBKZ        " 특별재고지시자
                       A~EMLIF     AS LIFNR
                       D~NAME_ORG1 AS LIFNR_TX " 공급처명
                       A~MENGE        " 수량
                       A~DMBTR        " 금액(현지통화)
                       A~WAERS        " 통화
                       A~BWART        " 이동유형

*                     H~BEIKZ           " MPI 추가

                       A~GRUND        " 이동사유
                       A~SHKZG        " 차변/대변 지시자
                       A~MEINS        " 기본단위
                       A~WAERS        " 통화
                       A~ZEILE        " 자재문서항목
                       E~MTART        " 자재유형
                       A~VGART            "CHECK
                       A~BUDAT            " 전기일 추가
                       A~SALK3        " 총평가액
                       A~LBKUM        " 총평가재고수량

                  INTO CORRESPONDING FIELDS OF TABLE GT_DISP_0500
                  FROM MATDOC AS A
                  LEFT OUTER JOIN MAKT AS B
                    ON B~MATNR EQ A~MATNR
                   AND B~SPRAS EQ SY-LANGU
                  LEFT OUTER JOIN BUT000 AS D
                    ON D~PARTNER EQ A~EMLIF
                  LEFT OUTER JOIN MARA AS E
                    ON E~MATNR EQ A~MATNR
                  JOIN ZMMPAT52010 AS H
                    ON H~BWART EQ A~BWART
                 WHERE A~RECORD_TYPE EQ 'MDOC'
                   AND A~BUDAT BETWEEN S_BUDAT-LOW AND S_BUDAT-HIGH
                   AND A~MATNR EQ <FS_MATNR>
                   AND A~WERKS EQ <FS_WERKS>
                   AND A~LGORT EQ <FS_LGORT>

                   AND A~CHARG EQ <FS_CHARG>

*                   AND A~BWART NOT IN ('541', '542', '543', '544'). " 사급 mvt 제외

                 AND A~SOBKZ NE 'O'. " 사급 제외

                APPEND LINES OF GT_DISP_0500 TO GT_MATDOC[].
                CLEAR GT_DISP_0500[].

              ELSE.

* 사급업체 있으면 사급 케이스 라인
*541, 542, 543, 544만

                SELECT A~BUKRS        " 회사코드
                       A~MJAHR        " 자재문서연도
                       A~MBLNR        " 자재문서번호
                       A~MATNR        " 자재번호
                       B~MAKTX        " 자재내역(명)
                       A~WERKS        " 플랜트
                       A~LGORT        " 저장위치
                       A~CHARG        " 배치(Batch)
                       A~SOBKZ        " 특별재고지시자
                       A~EMLIF     AS LIFNR
                       D~NAME_ORG1 AS LIFNR_TX " 공급처명
                       A~MENGE        " 수량
                       A~DMBTR        " 금액(현지통화)
                       A~WAERS        " 통화
                       A~BWART        " 이동유형

*                     H~BEIKZ           " MPI 추가

                       A~GRUND        " 이동사유
                       A~SHKZG        " 차변/대변 지시자
                       A~MEINS        " 기본단위
                       A~WAERS        " 통화
                       A~ZEILE        " 자재문서항목
                       E~MTART        " 자재유형
                       A~VGART            "CHECK
                       A~BUDAT            " 전기일 추가
                       A~SALK3        " 총평가액
                       A~LBKUM        " 총평가재고수량

                  INTO CORRESPONDING FIELDS OF TABLE GT_DISP_0500
                  FROM MATDOC AS A
                  LEFT OUTER JOIN MAKT AS B
                    ON B~MATNR EQ A~MATNR
                   AND B~SPRAS EQ SY-LANGU
                  LEFT OUTER JOIN BUT000 AS D
                    ON D~PARTNER EQ A~EMLIF
                  LEFT OUTER JOIN MARA AS E
                    ON E~MATNR EQ A~MATNR
                  JOIN ZMMPAT52010 AS H
                    ON H~BWART EQ A~BWART
                 WHERE A~RECORD_TYPE EQ 'MDOC'
                   AND A~BUDAT BETWEEN S_BUDAT-LOW AND S_BUDAT-HIGH
                   AND A~MATNR EQ <FS_MATNR>
                   AND A~WERKS EQ <FS_WERKS>
                   AND A~LGORT EQ <FS_LGORT>
                   AND A~EMLIF EQ <FS_LIFNR>
                   AND A~CHARG EQ <FS_CHARG>

*                   AND A~BWART IN ('541', '542', '543', '544'). " 사급 mvt만

                 AND A~SOBKZ EQ 'O'. " 사급재고만

                APPEND LINES OF GT_DISP_0500 TO GT_MATDOC[].
                CLEAR GT_DISP_0500[].
              ENDIF.
            ENDLOOP.

            IF GT_MATDOC[] IS INITIAL.
              " No data found
              MESSAGE S082 DISPLAY LIKE 'E'.
              EXIT.
            ENDIF.

*--STO 금액 변환

            DATA(LT_STO) = GT_MATDOC[].
            DELETE LT_STO WHERE DMBTR NE 0.
            DELETE LT_STO WHERE BWART NE '101'.

            SELECT A~MJAHR,           " 자재문서연도
                   A~MBLNR,           " 자재문서번호
                   A~ZEILE,           " 자재문서항목
                   A~MATNR,           " 자재번호
                   A~WERKS,           " 플랜트
                   A~LGORT_CID AS LGORT, " 저장위치
                   A~CHARG_CID AS CHARG, " 배치(Batch)
                   A~DMBTR            " 금액(현지통화)
              FROM MATDOC AS A JOIN @LT_STO AS B
                                 ON A~MJAHR     = B~MJAHR
                                AND A~MBLNR     = B~MBLNR
                                AND A~ZEILE     = B~ZEILE
                                AND A~MATNR     = B~MATNR
                                AND A~WERKS     = B~WERKS
                                AND A~LGORT_CID = B~LGORT
                                AND A~CHARG_CID = B~CHARG
             WHERE A~RECORD_TYPE = 'MDOC_CP'
               AND A~LBBSA_SID   = '06'
               AND A~DMBTR NE 0
              INTO TABLE @DATA(LT_STO_DMBTR).
            SORT LT_STO_DMBTR BY MJAHR MBLNR ZEILE MATNR WERKS LGORT CHARG.

*-- Group 및 차/대 반영

            LOOP AT GT_MATDOC[] INTO LS_MATDOC.

*--STO 금액 변환

              IF LS_MATDOC-BWART = '101' AND LS_MATDOC-DMBTR = 0.
                READ TABLE LT_STO_DMBTR INTO DATA(LS_STO_DMBTR) WITH KEY MJAHR = LS_MATDOC-MJAHR
                                                                         MBLNR = LS_MATDOC-MBLNR
                                                                         ZEILE = LS_MATDOC-ZEILE
                                                                         MATNR = LS_MATDOC-MATNR
                                                                         WERKS = LS_MATDOC-WERKS
                                                                         LGORT = LS_MATDOC-LGORT
                                                                         CHARG = LS_MATDOC-CHARG
                                                                         BINARY SEARCH.
                IF SY-SUBRC = 0.
                  LS_MATDOC-DMBTR = LS_STO_DMBTR-DMBTR.
                ENDIF.
              ENDIF.
              CLEAR LS_STO_DMBTR.

              READ TABLE GT_GROUP INTO LS_GROUP
                                  WITH KEY BWART = LS_MATDOC-BWART
                                  BINARY SEARCH.
              IF SY-SUBRC NE 0.
                CASE LS_MATDOC-SHKZG.
                  WHEN 'H'.
                    LS_MATDOC-ZGROUP = GV_GI_ETC.
                  WHEN 'S'.
                    LS_MATDOC-ZGROUP = GV_GR_ETC.
                ENDCASE.
              ELSE.
                LS_MATDOC-ZGROUP = LS_GROUP-ZGROUP.
              ENDIF.

              IF ( LS_MATDOC-ZGROUP(2) = 'GR' AND LS_MATDOC-SHKZG = 'H' ) OR
                 ( LS_MATDOC-ZGROUP(2) = 'GI' AND LS_MATDOC-SHKZG = 'H' ).
                LS_MATDOC-MENGE = LS_MATDOC-MENGE * -1.
                LS_MATDOC-DMBTR = LS_MATDOC-DMBTR * -1.
              ELSE.

*              <FS_RAW>-MENGE.
*              <FS_RAW>-DMBTR.

              ENDIF.

*

*-- Mvt.Text 추가

              SELECT SINGLE BTEXT
                     INTO @DATA(LV_BTEXT)
                     FROM T156T
                     WHERE BWART EQ @LS_MATDOC-BWART
                       AND SPRAS EQ @SY-LANGU.

              LS_MATDOC-BTEXT = LV_BTEXT.

**-- 생산오더 Number select
*                  INTO CORRESPONDING FIELDS OF LS_MATDOC

              APPEND LS_MATDOC TO GT_DISP_0500.
            ENDLOOP.

*-- 정의된 Mvt에 포함되지 않은 값은 Delete

            LOOP AT GT_DISP_0500 ASSIGNING FIELD-SYMBOL(<FS_DISP_0500>).

              READ TABLE GT_GROUP WITH KEY BWART = <FS_DISP_0500>-BWART TRANSPORTING NO FIELDS.

              IF SY-SUBRC <> 0.
                DELETE TABLE GT_DISP_0500 FROM <FS_DISP_0500>.

              ENDIF.

              IF <FS_DISP_0500>-MENGE < 0.
                <FS_DISP_0500>-INFO = 'C600'.
              ELSE.
                <FS_DISP_0500>-INFO = 'C100'.
              ENDIF.

            ENDLOOP.

            SORT GT_DISP_0500 BY WERKS LIFNR MATNR BUDAT.

            CALL SCREEN 0500 STARTING AT 10 2
            ENDING AT 170 30.

          ENDIF.
      ENDCASE.
  ENDCASE.

ENDFORM.

