*&---------------------------------------------------------------------*
*& INCLUDE ZMMPAR52000C01  (To-Be / ALV 모던화 v2)
*& ALV 이벤트 핸들러 — 단일 클래스 LCL_EVENT_RECEIVER + SY-DYNNR 분기
*& 표준: standards/patterns/ALV_MODERN_PATTERN.md §2 / §3-4
*&   - 구: LCL_EVENT_RECEIVER_100~500/110 (6벌) → 신: 단일 클래스 1벌
*&   - 기존 핸들러 FORM(HANDLE_DOUBLE_CLICK_100 등)은 그대로 재사용(로직 무변경)
*&   - 그리드 인스턴스는 MAIN/POP 2벌로 재사용되므로 SENDER가 아닌 SY-DYNNR로 화면 분기
*&---------------------------------------------------------------------*

*--------------------------------------------------------------------*
* 이벤트 핸들러 클래스 (단일)
*--------------------------------------------------------------------*
CLASS LCL_EVENT_RECEIVER DEFINITION.
  PUBLIC SECTION.

    METHODS HANDLE_DOUBLE_CLICK
      FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_ROW E_COLUMN SENDER.

    METHODS HANDLE_USER_COMMAND
      FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
      IMPORTING E_UCOMM SENDER.

    METHODS HANDLE_TOOLBAR
      FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
      IMPORTING E_OBJECT E_INTERACTIVE SENDER.

    METHODS ON_TOP_OF_PAGE
      FOR EVENT TOP_OF_PAGE OF CL_GUI_ALV_GRID
      IMPORTING E_DYNDOC_ID.

ENDCLASS.

CLASS LCL_EVENT_RECEIVER IMPLEMENTATION.

  METHOD HANDLE_DOUBLE_CLICK.
    " 화면별 더블클릭 분기 — 기존 핸들러 FORM 재사용
    CASE SY-DYNNR.
      WHEN '0100'. PERFORM HANDLE_DOUBLE_CLICK_100 USING E_ROW E_COLUMN.   " 메인
      WHEN '0400'. PERFORM HANDLE_DOUBLE_CLICK_400 USING E_ROW E_COLUMN.   " 배치(풀스크린)
      WHEN '0200'. PERFORM HANDLE_DOUBLE_CLICK_200 USING E_ROW E_COLUMN.   " 그룹 RAW(팝업)
      WHEN '0300'. PERFORM HANDLE_DOUBLE_CLICK_300 USING E_ROW E_COLUMN.   " SIT(팝업)
      WHEN '0500'. PERFORM HANDLE_DOUBLE_CLICK_500 USING E_ROW E_COLUMN.   " 자재문서(팝업)
    ENDCASE.
  ENDMETHOD.

  METHOD HANDLE_USER_COMMAND.
    " 사용자 커맨드 — 메인(0100)/배치(0400)만 처리
    CASE SY-DYNNR.
      WHEN '0100'. PERFORM HANDLE_USER_COMMAND_100 USING E_UCOMM SENDER.
      WHEN '0400'. PERFORM HANDLE_USER_COMMAND_400 USING E_UCOMM SENDER.
    ENDCASE.
  ENDMETHOD.

  METHOD HANDLE_TOOLBAR.
    " 툴바 — 0400 전용 / 그 외 공통
    CASE SY-DYNNR.
      WHEN '0400'. PERFORM HANDLER_TOOLBAR_0400 USING E_OBJECT SENDER.
      WHEN OTHERS. PERFORM HANDLER_TOOLBAR      USING E_OBJECT SENDER.
    ENDCASE.
  ENDMETHOD.

  METHOD ON_TOP_OF_PAGE.
    PERFORM TOP_OF_PAGE USING E_DYNDOC_ID.
  ENDMETHOD.

ENDCLASS.
