*&---------------------------------------------------------------------*
*& INCLUDE ZMMPAR52000SCR  (To-Be / 리팩토링: R+M)  — 셀렉션 스크린
*& 표준: standards/ABAP_CODE_STANDARD.md | 죽은 주석코드 정리 적용
*&---------------------------------------------------------------------*

Code listing for: ZMMPAR52000SCR Description: Include ZMMMAM36100SCR

*&---------------------------------------------------------------------*
*& Include          ZMMMAM36100SCR
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* SELECTION SCREEN
*----------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-005.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS : RB_MM TYPE C RADIOBUTTON GROUP R01 DEFAULT 'X' USER-COMMAND UC1 MODIF ID R01.
    SELECTION-SCREEN COMMENT (25) TEXT-R03 FOR FIELD RB_MM MODIF ID R01.
    PARAMETERS : RB_CO TYPE C RADIOBUTTON GROUP R01 MODIF ID  R01.
    SELECTION-SCREEN COMMENT (25) TEXT-R04 FOR FIELD RB_CO MODIF ID R01.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-001.

*PARAMETERS : P_LFGJA LIKE MBEWH-LFGJA .
*PARAMETERS : P_LFMON LIKE MBEWH-LFMON .

  PARAMETERS : P_SPMON TYPE SPMON DEFAULT SY-DATLO+0(6) MODIF ID CO1.
  SELECT-OPTIONS : S_BUDAT FOR MATDOC-BUDAT OBLIGATORY MODIF ID MM1,  " Year, Month 를 Period 로 변경 / 24.08.21
                   S_BUKRS FOR MATDOC-BUKRS DEFAULT '1088' NO INTERVALS NO-EXTENSION OBLIGATORY,
                   S_WERKS FOR MATDOC-WERKS DEFAULT '1010' NO INTERVALS NO-EXTENSION OBLIGATORY,
                   S_LGORT FOR MATDOC-LGORT,

*                   S_MTART FOR MARA-MTART, " DEFAULT 'HAWA',  "Add : 2020.12.31 "Update : 2024.08.07

                   S_MATNR FOR MATDOC-MATNR,
                   S_CHARG FOR MATDOC-CHARG MODIF ID CHG.

SELECTION-SCREEN END OF BLOCK BLOCK1.

*** Valuated/Batch Selection
*SELECTION-SCREEN BEGIN OF BLOCK BLOCK2 WITH FRAME TITLE TEXT-002.
*
*  SELECTION-SCREEN BEGIN OF LINE.
*    PARAMETERS: RA_R1 RADIOBUTTON GROUP GR1 USER-COMMAND SEL.
*    SELECTION-SCREEN COMMENT (20) TEXT-R01 FOR FIELD RA_R1.   " Valuated Stock
*  SELECTION-SCREEN END OF LINE.
*  SELECTION-SCREEN BEGIN OF LINE.
*    PARAMETERS: RA_R2 RADIOBUTTON GROUP GR1 DEFAULT 'X'.
*    SELECTION-SCREEN COMMENT (40) TEXT-R02 FOR FIELD RA_R2.   " Batch Stock
*  SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN END OF BLOCK BLOCK2.

" 2024.09.25 요구사항 추가 : MPI 조회 조건 반영

** MPI Selection

SELECTION-SCREEN BEGIN OF BLOCK BLOCK4 WITH FRAME TITLE TEXT-004.

*  PARAMETERS : P_VAL1 AS CHECKBOX DEFAULT 'X',   " Non-chargeable Component (V)
*               P_VAL2 AS CHECKBOX DEFAULT 'X'.   " Chargeable Component (A)

  PARAMETERS : P_VAL9 AS CHECKBOX.               " 사급자재

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (79) TEXT-C02.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (70) TEXT-C03.
  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLOCK4.

** Amount Selection

SELECTION-SCREEN BEGIN OF BLOCK BLOCK3 WITH FRAME TITLE TEXT-003.
  PARAMETERS : P_VAL AS CHECKBOX MODIF ID CO1.               " Amount
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (70) TEXT-C01 MODIF ID CO1.       " If you check the box, you can see amount value.
  SELECTION-SCREEN END OF LINE.
  "This is a reference value.
SELECTION-SCREEN END OF BLOCK BLOCK3.

Extracted by Mass Download version 1.5.5 - E.G.Mellodew. 1998-2026. Sap Release 755
